name: development
on:
  push:
    branches: [ development ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**.yml'
  #pull_request:
   # branches: [ development ]
   # paths-ignore:
   #   - '**.md'
   #   - '.gihub/workflows/**.yml'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    env:
      Solution_Name: HaleyWPF.sln                         

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core [latest version is 5.0.x]
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x # The core verion used with Haley is 3.1.0

    # Add  MSBuild 
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    #NO UNIT TEST IN WPF AT THE MOMENT

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
